### ISSUE TITLE
Re-design & Implement new RecipeCard and RecipeCardDetailed

### ISSUE THREAD

**Issue by j-blackmore** [j-blackmore/our-recipes#38]
# 🍀 Feature Request

It is time the RecipeCard and RecipeCardDetailed got a makeover. The detailed card is too small, and no longer shows all the information provided. Font is too small. Cards are not interesting. Yes lets keep it simple, but give it some flare whilst we're at it.

## 📝 TODO
- [x] Redesign the cards using an online tool (Figma)
- [ ] Implement the infrastructure for the new Recipe information
- [ ] Implement new designs
- [ ] Rename `RecipeCardDetailed` to `DetailedRecipeCard` to follow suit
----------------
❗Note: _This will be split up into multiple PRs as this is a large overhaul_
